import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/utils/Header";
import LocationComponent from "@/Components/utils/LocationComponent";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authcontent = cookies().get("AUTH")?.value;
  const authparsed = authcontent && JSON.parse(authcontent);

  return (
    <section className="w-screen">
      <Header />
      <LocationComponent response={authparsed && authparsed.counselor} />
      {children}
    </section>
  );
}
