import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/utils/Header";
import LocationComponent from "@/Components/utils/LocationComponent";
import { cookies } from "next/headers";
import HeaderCounselor from "@/Components/Ui/Headers/HeaderCounselor/HeaderCounselor";

export const metadata: Metadata = {
  title: "Counselor Care System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authcontent = cookies().get("AUTH")?.value;
  const authparsed = authcontent && JSON.parse(authcontent);

  return (
    <section className="w-screen overflow-x-hidden h-full">
      <HeaderCounselor response={authparsed && authparsed.counselor} />
      <LocationComponent response={authparsed && authparsed.counselor} />
      {children}
    </section>
  );
}
