import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Schedule Session",
  description: "Generated by CCS Portal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <section className="w-screen">{children}</section>;
}
