import type { Metadata } from "next";
import "./globals.css";
import GlobalStateManager from "@/Components/context/GlobalStateManager";
import Toast from "@/Components/context/Toast";

export const metadata: Metadata = {
  title: "ccs.sanjivanipune.com",
  description: "Generated by sanjivanipune.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" w-screen">
        <GlobalStateManager>
          {children} <Toast />
        </GlobalStateManager>
      </body>
    </html>
  );
}
